---
author: Alexander Wu
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE, error = TRUE, fig.height = 3)
library(tidyverse)
library(lubridate)
library(kableExtra)
library(broman)
library(scales)
library(modelr)
library(jsonlite)
theme_set(theme_minimal())
```

```{r}
education = read_csv("education.csv")
crime = read_csv("crime.csv")
employment = read_csv("employment.csv")
homeprice = read_csv("homeprice.csv")
```

```{r}
education$`Population`= education$`City&Population`
education$'City' = education$'City&Population'
education = education %>% 
  mutate(City = substr(education$City, 1, str_locate(education$City, ", WI / ") - 1), Population = substr(education$Population, str_locate(education$Population, " / ") + 3, nchar(education$Population))) %>% 
  select(`Average Education Index`, `Population`, `City`) %>% 
  mutate(Population = as.numeric(str_replace(Population, ",", "")))
#education$Population = as.numeric(gsub(",", "", education$Population))
```

```{r}
crime$`Population`= crime$`City&Population`
crime$'City' = crime$'City&Population'
crime = crime %>% 
  mutate(City = substr(crime$City, 1, str_locate(crime$City, ", WI / ") - 1)) %>% 
  select('Crime Index', 'City')
```

```{r}
homeprice$`Population`= homeprice$`City&Population`
homeprice$'City' = homeprice$'City&Population'
homeprice = homeprice %>% 
  mutate(City = substr(homeprice$City, 1, str_locate(homeprice$City, ", WI / ") - 1)) %>% 
  select('House Median Value', 'City')
```

```{r}
employment$`Population`= employment$`City&Population`
employment$'City' = employment$'City&Population'
employment = employment %>% 
  mutate(City = substr(employment$City, 1, str_locate(employment$City, ", WI / ") - 1)) %>%   
	rename('Age 16 or Older Population Employed Percentage' = 'Age 16 or Older Population Percentage') %>% 
	select('Age 16 or Older Population Employed Percentage', 'City')
```

```{r}
final = left_join(education, crime, "City")
final = left_join(final, employment, "City")
final = left_join(final, homeprice, "City")
final = drop_na(final) 
final = final[,c(3, 2, 1, 4, 5, 6)]
max_education_index = max(final$`Average Education Index`)
final = final %>% 
  filter(Population > 1000) %>% 
  rename(city = City, population = Population, average_education_index = "Average Education Index", crime_index = "Crime Index", sixteen_plus_employed_percentage = "Age 16 or Older Population Employed Percentage", house_median_value = "House Median Value") %>% 
  mutate(house_median_value = str_sub(str_replace(house_median_value, ",", ""), 2, -1),
         sixteen_plus_employed_percentage = str_replace(sixteen_plus_employed_percentage, "%", ""),
         edu_index_norm = average_education_index / max_education_index)
final$house_median_value = as.numeric(final$house_median_value)
final$sixteen_plus_employed_percentage = as.numeric(final$sixteen_plus_employed_percentage)
max_employment_percentage = max(final$sixteen_plus_employed_percentage)
final = final %>% 
  mutate(employed_percentage_norm = sixteen_plus_employed_percentage / max_employment_percentage)
ggplot(final, aes(x = crime_index)) +
  geom_density() +
  geom_vline(aes(xintercept=700), color="red", linetype = "dashed")
```

```{r}
final$'' = 1:264
final = final[,c(9, 1, 2, 3, 4, 5, 6, 7, 8)]
#write_csv(final, "city_education_crime_employment_homeprice.csv")
print(final$city)
write(final$city, "city_list.txt")
```

```{r}
cities = as.data.frame(final$city)
cities = rename(cities, "city" = "final$city")
us_cities_all = read_csv("uscities.csv")
cities_wi = us_cities_all %>% 
  filter(state_id == "WI")
city_lat_lng = left_join(cities, cities_wi, "city")
city_lat_lng = city_lat_lng %>% 
  select('city', 'lat', 'lng') %>% 
  rename('latitude' = 'lat', 'longitude' = 'lng')
city_lat_lng[17,2] = 43.0203
city_lat_lng[17,3] = -89.2828
city_lat_lng[71,2] = 45.4100
city_lat_lng[71,3] = -92.6266
city_lat_lng[115,2] = 43.335998656
city_lat_lng[115,3] = -90.38416513
city_lat_lng[126,2] = 44.05526
city_lat_lng[126,3] = -89.22623
city_lat_lng[129,2] = 42.9716
city_lat_lng[129,3] = -87.8730
city_lat_lng[139,2] = 43.7718
city_lat_lng[139,3] = -88.4397
city_lat_lng[175,2] = 44.92416297
city_lat_lng[175,3] = -89.83749665
city_lat_lng[184,2] = 43.0429
city_lat_lng[184,3] = -91.1372
city_lat_lng[249,2] = 43.8107
city_lat_lng[249,3] = -88.4860
city_lat_lng[20,2] = 43.056833106
city_lat_lng[20,3] = -88.242999028
city_lat_lng[33,2] = 43.076166362
city_lat_lng[33,3] = -88.25166566


write_csv(city_lat_lng, "city_lat_lng.csv")
json_data = toJSON(city_lat_lng)
writeLines(json_data, "city_lat_lng.json")
```
